PREFIX bsbm: <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/>
PREFIX rev: <http://purl.org/stuff/rev#>

SELECT ?country (COUNT(DISTINCT ?reviewer) as ?total)
FROM<http://bsbmScale10000.com>
WHERE {
    ?a rev:reviewer ?reviewer .
    ?reviewer bsbm:country ?country .
} GROUP BY (?country)