//g2
prefix bsbm: <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/>

SELECT ?review ?rating1
FROM<http://bsbmScale1000.com>
WHERE {
    ?review bsbm:reviewFor <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/instances/dataFromProducer9/Product451> .
    ?review bsbm:rating1 ?rating1 .
} GROUP BY (?rating1)