//l1

PREFIX bsbm: <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/>

SELECT distinct ?rating1
FROM<http://bsbmScale1000.com>
WHERE {
 ?review bsbm:reviewFor <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/instances/dataFromProducer8/Product343> .
 ?review bsbm:rating1 ?rating1 .
}
LIMIT 2