PREFIX bsbm: <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/>
PREFIX rev: <http://purl.org/stuff/rev#>

SELECT ?reviewer (COUNT (?product) as ?total)
FROM<http://bsbmScale1000.com>
WHERE {
    ?review bsbm:reviewFor ?product .
    ?review rev:reviewer ?reviewer .
}
GROUP BY (?reviewer)
ORDER BY DESC (?total)
LIMIT 10